-- Foundation Studio · PostgreSQL execution SQL

-- foundation:stage 4
CREATE TABLE silver."silver_lims_curitiba" (
              source_row_number integer PRIMARY KEY,
              "sample_id" text,
"product_line" text,
"material_code" text,
"batch_lot_number" text,
"container_id" text,
"test_type" text,
"test_method_version" text,
"instrument_id" text,
"analyst_id" text,
"reviewer_id" text,
"date_requested" timestamp,
"date_received" timestamp,
"date_started" timestamp,
"date_completed" timestamp,
"priority" text,
"submitter" text,
"project_reference" text,
"result_value" numeric,
"result_unit" text,
"spec_lower_limit" numeric,
"spec_upper_limit" numeric,
"sample_status" text,
"approval_status" text,
"approval_date" timestamp,
"storage_location" text,
"retest_flag" boolean,
"comments" text,
"site_code" text,
              source_table text NOT NULL,
              cleansed_at timestamptz NOT NULL DEFAULT now()
            );

-- foundation:stage 5
INSERT INTO silver."silver_lims_curitiba" (
              source_row_number, "sample_id", "product_line", "material_code", "batch_lot_number", "container_id", "test_type", "test_method_version", "instrument_id", "analyst_id", "reviewer_id", "date_requested", "date_received", "date_started", "date_completed", "priority", "submitter", "project_reference", "result_value", "result_unit", "spec_lower_limit", "spec_upper_limit", "sample_status", "approval_status", "approval_date", "storage_location", "retest_flag", "comments", "site_code", source_table
            )
            SELECT "row_data"."source_row_number",
  "row_data"."sample_id" AS "sample_id",
  "row_data"."product_line" AS "product_line",
  "row_data"."material_code" AS "material_code",
  "row_data"."batch_lot_number" AS "batch_lot_number",
  "row_data"."container_id" AS "container_id",
  COALESCE((SELECT "ref"."governed_standard_reference" FROM "reference_data"."governed_astm_ilsac_test_method_reference" AS "ref" WHERE LOWER(TRIM(CAST("ref"."source_method_name" AS VARCHAR))) = LOWER(TRIM(CAST("row_data"."test_type" AS VARCHAR)))), NULL) AS "test_type",
  "row_data"."test_method_version" AS "test_method_version",
  "row_data"."instrument_id" AS "instrument_id",
  "row_data"."analyst_id" AS "analyst_id",
  "row_data"."reviewer_id" AS "reviewer_id",
  "row_data"."date_requested" AS "date_requested",
  "row_data"."date_received" AS "date_received",
  "row_data"."date_started" AS "date_started",
  "row_data"."date_completed" AS "date_completed",
  "row_data"."priority" AS "priority",
  "row_data"."submitter" AS "submitter",
  NULL AS "project_reference",
  "row_data"."result_value" AS "result_value",
  COALESCE((SELECT "ref"."governed_unit" FROM "reference_data"."governed_uom_reference" AS "ref" WHERE LOWER(TRIM(CAST("ref"."source_unit" AS VARCHAR))) = LOWER(TRIM(CAST("row_data"."result_unit" AS VARCHAR)))), NULL) AS "result_unit",
  NULL AS "spec_lower_limit",
  NULL AS "spec_upper_limit",
  COALESCE((SELECT "ref"."governed_status" FROM "reference_data"."governed_sample_status_reference" AS "ref" WHERE LOWER(TRIM(CAST("ref"."source_value" AS VARCHAR))) = LOWER(TRIM(CAST("row_data"."sample_status" AS VARCHAR)))), NULL) AS "sample_status",
  "row_data"."approval_status" AS "approval_status",
  NULL AS "approval_date",
  NULL AS "storage_location",
  "row_data"."retest_flag" AS "retest_flag",
  "row_data"."comments" AS "comments",
  "row_data"."site_code" AS "site_code",
  'lims_curitiba_amostras' AS "source_table"
FROM (SELECT "row_data".* FROM "bronze"."lims_curitiba_amostras" AS "row_data" WHERE NOT (COALESCE(((SELECT "ref"."governed_standard_reference" FROM "reference_data"."governed_astm_ilsac_test_method_reference" AS "ref" WHERE LOWER(TRIM(CAST("ref"."source_method_name" AS VARCHAR))) = LOWER(TRIM(CAST("row_data"."test_type" AS VARCHAR)))) IS NULL), FALSE) OR COALESCE(((SELECT "ref"."governed_unit" FROM "reference_data"."governed_uom_reference" AS "ref" WHERE LOWER(TRIM(CAST("ref"."source_unit" AS VARCHAR))) = LOWER(TRIM(CAST("row_data"."result_unit" AS VARCHAR)))) IS NULL), FALSE) OR COALESCE(((SELECT "ref"."governed_status" FROM "reference_data"."governed_sample_status_reference" AS "ref" WHERE LOWER(TRIM(CAST("ref"."source_value" AS VARCHAR))) = LOWER(TRIM(CAST("row_data"."sample_status" AS VARCHAR)))) IS NULL), FALSE))) AS "row_data";
